---
title: "Sporulation dynamics in response to extreme energy limitation"
author: "Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
editor_options: 
  chunk_output_type: console
---

# Working dir & packages
```{r}
# Set working directory and load packages
rm(list = ls())
getwd()
setwd("~/Github/SporMut/code/3.Biofilm")

require("ggplot2")
require("cowplot")
require("reshape2")
require("ggpubr")
require("dplyr")
require("scales")
require("grid")
require("png")

require("rstan")
require("devtools")
#install_github("paul-buerkner/brms")
library(brms)
library(bayestestR)
library(bayesplot)

sem <- function(x, ...){sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))}

#For jags bayesian - Don 
library(rjags)
library(ggridges) # ridge plots 
```

# Load data
```{r}
BacillusBiofilm <- read.table("~/GitHub/SporMut/data/3.Biofilm/Biofilm_06_16_20.txt", sep= "\t", header = FALSE)
```

# Format data by plate
```{r}
###100 Lines
Plate1BS<- BacillusBiofilm[which(BacillusBiofilm$V1=='plate1'),] 
Plate2BS<- BacillusBiofilm[which(BacillusBiofilm$V1=='plate2'),] 

names(Plate1BS)<- as.matrix(Plate1BS[1,])
Plate1BS<- Plate1BS[-1,]
Plate1BS[]<-lapply(Plate1BS,function(x) type.convert(as.character(x)))
Plate1BS
names(Plate2BS)<- as.matrix(Plate2BS[1,])
Plate2BS<- Plate2BS[-1,]
Plate2BS[]<-lapply(Plate2BS,function(x) type.convert(as.character(x)))
Plate2BS

Plate1BSMelt<-melt(Plate1BS,id=c("plate1", "Replicate"))
names(Plate1BSMelt)<-c("Plate","Replicate","Sample","OD550")
Plate1BSMelt

Plate2BSMelt<-melt(Plate2BS,id=c("plate2", "Replicate"))
names(Plate2BSMelt)<-c("Plate","Replicate","Sample","OD550")
Plate2BSMelt
```

# Identify Samples
```{r}
#NonSpore <- BacillusCurveMelt$Sample %in% c("M4", "M13", "M17" , "M19", "M21", "M41", "M54", "M79")
#Spore<-BacillusCurveMelt$Sample %in% c( "M23", "M26", "S1", "S6", "S11", "S22", "S51", "S95")

Blank <- Plate1BSMelt$Sample %in% c("Blank1")
Spore<-Plate1BSMelt$Sample %in% c( "M23", "M26")
Vegetative<-Plate1BSMelt$Sample %in% c("M4", "M13", "M17" , "M19", "M21", "M41", "M54", "M79")
Ancestor<-Plate1BSMelt$Sample %in% c( "Ancestor")
sinR<-Plate1BSMelt$Sample %in% c("M17" , "M19", "M21", "M41", "M54")
ywcC<-Plate1BSMelt$Sample %in% c("M4", "M13", "M79")

Plate1BSMelt$Treatment[Blank] <- "Blank"
Plate1BSMelt$Treatment[Spore] <- "Spore"
Plate1BSMelt$Treatment[Vegetative] <- "Vegetative"
Plate1BSMelt$Treatment[Ancestor] <- "Ancestor"
Plate1BSMelt$BiofilmMut[Ancestor] <- "Ancestor"
Plate1BSMelt$BiofilmMut[sinR] <- "Vegetative:sinR"
Plate1BSMelt$BiofilmMut[ywcC] <- "Vegetative:ywcC/slrR"
Plate1BSMelt$BiofilmMut[Spore] <- "Spore"
Plate1BSMelt$BiofilmMut[Blank] <- "Blank"

Plate1BSMelt

Blank <- Plate2BSMelt$Sample %in% c("Blank1", "Blank2", "Blank3", "Blank4", "Blank5", "Blank6")
Spore<-Plate2BSMelt$Sample %in% c( "S1", "S6","S22","S52","S95")

Plate2BSMelt$Treatment[Blank] <- "Blank"
Plate2BSMelt$Treatment[Spore] <- "Spore"
Plate2BSMelt$BiofilmMut[Blank] <- "Blank"
Plate2BSMelt$BiofilmMut[Spore] <- "Spore"

Plate2BSMelt
```

# Correct OD for Blank
```{r}
Plate1BSBlankOnly<- Plate1BSMelt[which(Plate1BSMelt$Treatment=='Blank'),] 
Plate2BSBlankOnly<- Plate1BSMelt[which(Plate1BSMelt$Treatment=='Blank'),] 

Plate1BSMelt$BlankAvg<-median(Plate1BSBlankOnly$OD550)
Plate2BSMelt$BlankAvg<-median(Plate2BSBlankOnly$OD550)

Plate1BSMelt$OD550_Corrected<-Plate1BSMelt$OD550-Plate1BSMelt$BlankAvg
Plate2BSMelt$OD550_Corrected<-Plate2BSMelt$OD550-Plate2BSMelt$BlankAvg

Plate1BSMelt$OD550_Corrected[Plate1BSMelt$OD550_Corrected<=0] <- 0.00001
Plate2BSMelt$OD550_Corrected[Plate2BSMelt$OD550_Corrected<=0] <- 0.00001
```
# Bayesian stats with brms - Canan 

```{r}
set.seed(101423)
biofilmData <- Plate1BSMelt %>%
  mutate(mutation = case_when(
    BiofilmMut == "Vegetative:ywcC/slrR" ~ "ywcC/slrR", 
    BiofilmMut == "Vegetative:sinR" ~ "sinR",
    BiofilmMut == "Spore" ~ "spore", 
    BiofilmMut == "Ancestor" ~"ancestor")) %>%
  filter(!BiofilmMut == "Blank") %>%
  mutate(clones = gsub(pattern = '([[:upper:]])', perl = TRUE, replacement = '\\L\\1', Sample)) 

biofilmData$clones <- factor(biofilmData$clones, levels = c("ancestor", 
           "m4", "m13", "m79", "m17", "m19", "m21", "m41", "m54", "m23", "m26"))

write.csv(biofilmData, file = "biofil.csv", row.names = FALSE)

summary(lm(OD550_Corrected ~ clones, biofilmData))

get_prior(OD550_Corrected ~ 0 + clones,
                    data = biofilmData, family = gaussian())

prior1 <- prior(student_t(3, 0, 2.5), class = sigma)

m1 <- brm(OD550_Corrected ~ clones, data = biofilmData,
          family = "gaussian", prior = prior1)
summary(m1)
posterior_summary(m1)

rr <- rope_range(m1)
#-0.1 * sd(y), 0.1 * sd(y)
result1 <- describe_posterior(m1, centrality = c("median", "mean"),
                          rope_ci = 0.95, 
                          ci = 0.95,
                          ci_method = "HDI", 
                          test = c("equivalence_test", "p_direction", "p_significance"),
                          rope_range = rr, 
                          diagnostic = "Rhat")

result2 <- equivalence_test(m1, 
                          rope_ci = 0.95, 
                          ci = 0.95,
                          ci_method = "HDI", 
                          rope_range = rr)
plot(result2, stack = FALSE)

####################################################################################
m2 <- brm(OD550_Corrected ~ mutation + (1|clones), data = biofilmData,
          family = "gaussian")
summary(m2)
posterior_summary(m2)

result2.1 <- describe_posterior(m1, centrality = c("median", "mean"),
                          rope_ci = 0.95, 
                          ci = 0.95,
                          ci_method = "HDI", 
                          test = c("equivalence_test", "p_direction", "p_significance"),
                          rope_range = rr, 
                          diagnostic = "Rhat")

result2.2 <- equivalence_test(m2, 
                          rope_ci = 0.95, 
                          ci = 0.95,
                          ci_method = "HDI", 
                          rope_range = rr, 
                          effects = "fixed")
plot(result2.2)
result2.3 <- equivalence_test(m2, 
                          rope_ci = 0.95, 
                          ci = 0.95,
                          ci_method = "HDI", 
                          rope_range = rr, 
                          effects = "random")
```

# Plots - Canan
```{r}
mytheme <- theme_bw()+
  theme(legend.position = 'none')+
  theme(axis.ticks.length = unit(.25, "cm"))+
  theme(legend.text = element_text(size=12))+
  theme(axis.text = element_text(size = 14), axis.title.y = element_text(size = 14), axis.title.x = element_text(size = 14))+
  #theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(strip.text.x = element_text(size = 14))

color_scheme_set("blue")

pars <- c("b_clonesm4", "b_clonesm13", "b_clonesm79", "b_clonesm17", "b_clonesm19", "b_clonesm21", "b_clonesm41", "b_clonesm54", "b_clonesm23", "b_clonesm26")

labels <- rev(c('m26','m23','m54','m41','m21','m19','m17','m79','m13','m4'))

posteriorB1 <- as.array(m1)
summary(m1)

# Biofilm 
B1 <- mcmc_areas(posteriorB1, pars = pars,
  prob = 0.95, # 95% intervals
  prob_outer = 1)+
  geom_vline(xintercept = rope_range(m1), linetype = "dashed", color = "grey25")+
  annotate("rect", xmin = rope_range(m1)[1], xmax = rope_range(m1)[2], ymin = -Inf, ymax = Inf,
           alpha = .2,fill = "grey")+
  scale_y_discrete(labels = labels)+
  scale_x_continuous(breaks = c(-0.5, 0, 0.5, 1, 1.5), labels = c(-1.5, 1, 1.5, 2, 2.5))+
  xlab("Relative change")+
 ggtitle("Biofilm - posterior distributions",
"medians and 95% credible intervals")+mytheme
ggsave("Biofilm-clones.pdf", B1, height = 5, width = 5)

posteriorB2 <- as.array(m2)

# Mixed effect model 
pars_random <- c ("r_clones[m4,Intercept]", "r_clones[m13,Intercept]", "r_clones[m79,Intercept]", "r_clones[m17,Intercept]", "r_clones[m19,Intercept]", "r_clones[m21,Intercept]", "r_clones[m41,Intercept]", "r_clones[m54,Intercept]", "r_clones[m23,Intercept]", "r_clones[m26,Intercept]")  

pars_fixed <- c( "b_mutationywcCDslrR", "b_mutationsinR", "b_mutationspore")
labels_fixed <- rev(c('spore', 'sinR', 'ywcC/slrR'))

# Random effects 
B2_random <- mcmc_areas(posteriorB2, pars = pars_random,
  prob = 0.95, # 95% intervals
  prob_outer = 1)+
  geom_vline(xintercept = rope_range(m2), linetype = "dashed", color = "grey25")+
  annotate("rect", xmin = rope_range(m2)[1], xmax = rope_range(m2)[2], ymin = -Inf, ymax = Inf,
           alpha = .2,fill = "grey")+
  scale_y_discrete(labels = labels)+
  #scale_x_continuous(breaks = c(-0.1, 0, 0.1), labels = c(-1.1, 1, 1.1))+
  xlab("Relative change")+
 ggtitle("Biofilm - random")+
  mytheme
ggsave("biofilm-random.pdf", B2_random, height = 5, width = 5)

equivalence_test(m2, effects = "fixed")
equivalence_test(m2, effects = "random")

# Fixed effects

B2_fixed <- mcmc_areas(posteriorB2, pars = pars_fixed,
  prob = 0.95, # 95% intervals
  prob_outer = 1)+
  geom_vline(xintercept = rope_range(m2), linetype = "dashed", color = "grey25")+
  annotate("rect", xmin = rope_range(m2)[1], xmax = rope_range(m2)[2], ymin = -Inf, ymax = Inf,
           alpha = .2,fill = "grey")+
  scale_y_discrete(labels = labels_fixed)+
  scale_x_continuous(breaks = c(-2, 0, 2), labels = c(-3, 1, 3))+
  xlab("Relative change")+
 ggtitle("Biofilm - fixed")+
  mytheme
ggsave("biofilm-fixed.pdf", B2_fixed, height = 5, width = 5)

```


```{r}
mytheme <- theme_bw()+
  theme(legend.position = 'none')+
  theme(axis.ticks.length = unit(.25, "cm"))+
  theme(legend.text = element_text(size=12))+
  theme(axis.text = element_text(size = 14), axis.title.y = element_text(size = 14), axis.title.x = element_text(size = 14))+
  #theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(strip.text.x = element_text(size = 14))

color_scheme_set("blue")

pars <- c("b_clonesm4", "b_clonesm13", "b_clonesm79", "b_clonesm17", "b_clonesm19", "b_clonesm21", "b_clonesm41", "b_clonesm54", "b_clonesm23", "b_clonesm26")

labels <- rev(c('m26','m23','m54','m41','m21','m19','m17','m79','m13','m4'))

posteriorB1 <- as.array(m1)
summary(m1)

# Biofilm 
B1 <- mcmc_areas(posteriorB1, pars = pars,
  prob = 0.95, # 95% intervals
  prob_outer = 1)+
  geom_vline(xintercept = rope_range(m1), linetype = "dashed", color = "grey25")+
  annotate("rect", xmin = rope_range(m1)[1], xmax = rope_range(m1)[2], ymin = -Inf, ymax = Inf,
           alpha = .2,fill = "grey")+
  scale_y_discrete(labels = labels)+
  scale_x_continuous(breaks = c(-0.5, 0, 0.5, 1, 1.5), labels = c(-1.5, 1, 1.5, 2, 2.5))+
  xlab("Relative change")+
 ggtitle("Biofilm - posterior distributions",
"medians and 95% credible intervals")+mytheme
ggsave("Biofilm-clones.pdf", B1, height = 5, width = 5)

posteriorB2 <- as.array(m2)

# Mixed effect model 
pars_random <- c ("r_clones[m4,Intercept]", "r_clones[m13,Intercept]", "r_clones[m79,Intercept]", "r_clones[m17,Intercept]", "r_clones[m19,Intercept]", "r_clones[m21,Intercept]", "r_clones[m41,Intercept]", "r_clones[m54,Intercept]", "r_clones[m23,Intercept]", "r_clones[m26,Intercept]")  

pars_fixed <- c( "b_mutationywcCDslrR", "b_mutationsinR", "b_mutationspore")
labels_fixed <- rev(c('spore', 'sinR', 'ywcC/slrR'))

# Random effects 
B2_random <- mcmc_areas(posteriorB2, pars = pars_random,
  prob = 0.95, # 95% intervals
  prob_outer = 1)+
  geom_vline(xintercept = rope_range(m2), linetype = "dashed", color = "grey25")+
  annotate("rect", xmin = rope_range(m2)[1], xmax = rope_range(m2)[2], ymin = -Inf, ymax = Inf,
           alpha = .2,fill = "grey")+
  scale_y_discrete(labels = labels)+
  #scale_x_continuous(breaks = c(-0.1, 0, 0.1), labels = c(-1.1, 1, 1.1))+
  xlab("Relative change")+
 ggtitle("Biofilm - random")+
  mytheme
ggsave("biofilm-random.pdf", B2_random, height = 5, width = 5)

equivalence_test(m2, effects = "fixed")
equivalence_test(m2, effects = "random")

# Fixed effects

B2_fixed <- mcmc_areas(posteriorB2, pars = pars_fixed,
  prob = 0.95, # 95% intervals
  prob_outer = 1)+
  geom_vline(xintercept = rope_range(m2), linetype = "dashed", color = "grey25")+
  annotate("rect", xmin = rope_range(m2)[1], xmax = rope_range(m2)[2], ymin = -Inf, ymax = Inf,
           alpha = .2,fill = "grey")+
  scale_y_discrete(labels = labels_fixed)+
  scale_x_continuous(breaks = c(-2, 0, 2), labels = c(-3, 1, 3))+
  xlab("Relative change")+
 ggtitle("Biofilm - fixed")+
  mytheme
ggsave("biofilm-fixed.pdf", B2_fixed, height = 5, width = 5)

```

# Jags model - Don - Relative
```{r}
# Jay's theme
mytheme <- theme_bw()+
  theme(axis.ticks.length = unit(.25, "cm"))+
  theme(legend.text = element_text(size=12))+
  theme(axis.text = element_text(size = 14), axis.title.y = element_text(size = 14), 
        axis.title.x = element_text(size = 14))+
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
      panel.border = element_rect(fill=NA, colour = "black", 
size=1))+
theme(strip.text.x = element_text(size = 14))+
  theme(legend.title=element_blank())+
  theme(panel.border = element_rect(fill=NA, colour = "black", 
size=1)) +
theme(axis.text.x.top = element_blank(), axis.title.x.top = element_blank(),
        axis.text.y.right = element_blank(), axis.title.y.right = element_blank())+
   theme(axis.title.x = element_text(margin=margin(10,0,0)),
   axis.title.y = element_text(margin=margin(0,10,0,0)),
   axis.text.x = element_text(margin=margin(10,0,0,0)),
   axis.text.y = element_text(margin=margin(0,10,0,0)))

#load data
input_dat <- read.table("~/GitHub/SporMut/code/3.Biofilm/biofil.csv", sep= ",", header = T)

#grab the clone names
clns<-c("m4","m13","m17","m19","m21","m23","m26","m41","m54","m79","ancestor")
ord_list<-rep(clns,each=8)

#put this is form this code used previously
dat<-split(input_dat,f=factor(ord_list,levels = clns))

#set up data for analyses
#var.mat<-data.frame(sapply(dat,"[",8))^2

#make weights based on inverse variance within clones
#wts_mat<-sweep(1/var.mat,MARGIN = 2,STATS =colSums(1/var.mat) ,FUN = "/")

#find weighted means
#apply(as.data.frame(sapply(dat,"[",8))*as.matrix(wts_mat),2,sum)

#create a long-form data.frame for later use
biofilm_df<-data.frame(biofilm=stack(as.data.frame(sapply(dat,"[",8)))$values,                           lvl=as.factor(sapply(strsplit(as.character(stack(as.data.frame(sapply(dat,"[",8)))$ind),"\\."),"[",1)))
# now let's do it bayes-style. from what I gather from the code, the sampling is simply done using the 6
# replicates for each clone and the ancestor. So, I will do that I will assume that the umax for each rep (for each clone)
# is sampling a population mean. in addition, will use the umax_se to define weights

#make a jags model that estimates a umax for the replicates of clones and the ancestor,
# using the weights the estimates. we will sample a log-normal dist for umax to make
# sure the estimates are all positive during sampling and assume each clone is sampling a dist
# with unique variance                   
mod<-"model{
     for(i in 1:8){
       for(j in 1:10){
       #here is the model for each clone
       M_mu[i,j]~dlnorm(mu_m[j],tau_m[j])
       #M_mu[i,j]~dlnorm(mu_m[j],tau_m[j])
       }
       #here is the model of the ancestor
      An_mu[i]~dlnorm(mu_a,tau_a)
      #An_mu[i]~dlnorm(mu_a,tau_a)
     }
     #priors
     for(i in 1:10){
      mu_m[i]~dnorm(0,.001)
      tau_m[i]~dgamma(.01,.01)
     }
     mu_a~dnorm(0,.001)
     tau_a~dgamma(.01,.01)
}"     

#Fit it
#gather data to feed jags
jdat<-list("M_mu"=as.data.frame(sapply(dat,"[",8))[,-11],"An_mu"=dat[['ancestor']]$OD550_Corrected)

#build the model object
jmod<-jags.model(textConnection(mod),n.chains = 4,data = jdat,n.adapt = 1000)

#update it
update(jmod,1000)

#sample it
ans<-coda.samples(jmod,c("mu_m","mu_a"),10000)

#look at plot to make sure they converge
#plot(ans)

#the samples look great so sets peek at the summaries of the posterior dists
summ<-summary(ans)

#check out the median of the posterior estimates

# we exponentiate them because we used a log-normal
exp(summ$quantiles)
exp(summ$quantiles[,"50%"])

#lets compare these medians with the simple weighted means
apply(as.data.frame(sapply(dat,"[",8)),2,sum)
#nice. all makes sense and is working

##Let's calculate the relative fitness across all chains
#combine all of the chains
vals<-rbind(as.matrix(ans[[1]]),as.matrix(ans[[2]]),as.matrix(ans[[3]]),as.matrix(ans[[4]]))

#find the quartiles of the relative fitness
apply(vals,2,function(x)median(exp(x)))

#calc relative fitness for rest of clones and plot them in a style
#similar to umax
plt_qnts<-matrix(0,10,3)
rownames(plt_qnts)<-clns[-11]
colnames(plt_qnts)<-c("2.5%","50%","97.5%")
for(i in 1:10)plt_qnts[i,]<-quantile(exp(vals[,i+1])/exp(vals[,1]),c(.025,.5,.975))

#plot the results 
plt_qnts_dat <- as.data.frame(plt_qnts)
plt_qnts_dat$clones <- rownames(plt_qnts_dat)
plt_qnts_dat$clones <- factor(plt_qnts_dat$clones, c("m4", "m13", "m79", "m17", "m19", "m21", "m41", "m54", "m23", "m26"))

biofilmplot <- ggplot(plt_qnts_dat, aes(y = clones, x = log10(plt_qnts_dat[,2]), group = clones))+
  geom_vline(xintercept = 0, linetype = "dashed")+
  geom_point(size = 4, shape = 21, color = "darkblue", fill = "white")+
  geom_errorbar(aes(xmin =log10(plt_qnts_dat[,1]), xmax =log10(plt_qnts_dat[,3])), width = 0, linewidth =1, color = "darkblue")+
  mytheme+
  xlab("Relative biofilm")+
  theme(axis.title.y = element_blank())
ggsave("biofilmJags_relative.pdf", biofilmplot, width = 5, height = 6)


#plot as distribution
data_df <- as.data.frame(exp(vals))
data_df_rel <- log10(data_df[,2:11]/data_df[,1])
names(data_df_rel) <- clns[-11]

data_long <- data_df_rel %>%
  tidyr::pivot_longer(cols = m4:m79, names_to = "clones", values_to = "dists")

data_long$clones <- factor(data_long$clones, c("m4", "m13", "m79", "m17", "m19", "m21", "m41", "m54", "m23", "m26"))

clone <- levels(data_long$clones)
clones <- c("m4", "m13", "m79", "m17", "m19", "m21", "m41", "m54", "m23", "m26")

dist.bio.rel <- ggplot(data_long, aes(y = as.numeric(clones), x = dists, group = clones, 
                           fill = 0.5 - abs(0.5 - stat(ecdf))))+
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey25")+
  stat_density_ridges(geom = "density_ridges_gradient", calc_ecdf = TRUE, 
                      rel_min_height = 0.005, alpha = 0.5, scale = 2, color = "grey25" )+
  xlab(expression(paste("Relative biofilm, ", italic(log[10]), sep="")))+
  scale_x_continuous(limits = c(-1.5, 1.5), sec.axis=dup_axis())+
  mytheme+
  theme(legend.position = c(.85,.8))+
   scale_fill_gradient(low = "white", high = "grey50",
                      name = "Tail prob.")+
   theme(axis.title.y = element_blank())+
  scale_y_continuous(breaks = 1:length(clone),
                     labels = clones,
                     sec.axis = sec_axis(~.,
                                         breaks = 1:length(clone),
                                         labels = clones))

ggsave("biofilm_jags_dist_log.pdf", dist.bio.rel, width = 5, height = 5)

# For reporting 

data_df_rel2 <- data_df[,2:11]/data_df[,1]
names(data_df_rel2) <- clns[-11]

data_long2 <- data_df_rel2 %>%
  tidyr::pivot_longer(cols = m4:m79, names_to = "clones", values_to = "dists")%>%
   group_by(clones) %>% 
  summarise(
    Q1 = quantile(dists, 0.25, na.rm = T),
    Median = quantile(dists, 0.5, na.rm = T),
    Q3 = quantile(dists, 0.975, na.rm = T)
  )

data_df_rel3 <- data_long2 %>% 
  mutate(mutation = c('ywc', 'sin', 'sin', 'sin', 'spore', 'spore', 
                      'ywc', 'sin', 'sin', 'ywc')) %>%
group_by(mutation) %>% 
  summarise(
    Q1 = mean(Q1),
    Median = mean(Median),
    Q3 = mean(Q3)
  )

names(data_df) <-  c("ancestor", "m4", "m13", "m17", "m19", "m21", "m23", "m26", "m41", "m54", "m79")

data_long_abs <- data_df %>%
  tidyr::pivot_longer(cols = ancestor:m79, names_to = "clones", values_to = "dists") %>%
  group_by(clones) %>% 
  summarise(
    Q1 = quantile(dists, 0.25, na.rm = T),
    Median = quantile(dists, 0.5, na.rm = T),
    Q3 = quantile(dists, 0.975, na.rm = T)
  )
  


```

# Jags model - Don - Coefficients - OVERWRITES
```{r}
#Do the same analysis but in the way that Lennon Lab did it
#Next I will do this with the long-form data
biofilm_df<-data.frame(biofilm=stack(as.data.frame(sapply(dat,"[",8)))$values,                           lvl=as.factor(sapply(strsplit(as.character(stack(as.data.frame(sapply(dat,"[",8)))$ind),"\\."),"[",1)))
#set up data for one-hot coding
one_hot<-cbind(ancestor=rep(1,dim(biofilm_df)[1]),sapply(clns[-11],function(x)as.numeric(biofilm_df$lvl==x)))

#this model is using a Gaussian with a single variance and fitting the 
# ancestor as the intercept and each clone as a different beta coef. The same as 
# you would get from the R formula umax~clone where the ancestor is coded as the first factor in "clone"
# here we use a different version of the weights because we don't want them relative by clone 
mod_1<-"model{
     for(i in 1:n){
       y[i]~dnorm(mu[i],tau/wts[i])
       mu[i]<-inprod(X[i,],b)
     }
     #priors
     for(i in 1:11){
      b[i]~dnorm(0,.001)
     }
     tau~dgamma(.01,.01)
     
}"     
#Fit it

jdat<-list("y"=biofilm_df$biofilm,"X"=one_hot,"n"=dim(biofilm_df)[1],"wts"=1000*stack(var.mat)$value)
jmod_1<-jags.model(textConnection(mod_1),n.chains = 4,data = jdat,n.adapt = 1000)
update(jmod_1,1000)
#sample the betas. we will use these to reconstruct the previous graph and the umax-clones.pdf graph
bio_dif<-coda.samples(jmod_1,c("b"),10000)
summary(bio_dif)
# let's peek at the tau to make sure it is converging 
#plot(coda.samples(jmod_1,c("tau"),10000))

#next, we will use the posterior chains to create relative fitness from coefs
biovals<-rbind(as.matrix(bio_dif[[1]]),as.matrix(bio_dif[[2]]),as.matrix(bio_dif[[3]]),as.matrix(bio_dif[[4]]))
rel_fit<-t(sapply(paste0("b[",2:11,"]"),function(x)quantile((as.matrix(biovals)[,"b[1]"]+as.matrix(biovals)[,x])/(as.matrix(biovals)[,"b[1]"]),c(.025,.5,.975))))
rownames(rel_fit)<-clns[-11]

rel_fit_dat <- as.data.frame(rel_fit)
rel_fit_dat$clones <- rownames(rel_fit_dat)
rel_fit_dat$clones <- factor(rel_fit_dat$clones, c("m4", "m13", "m79", "m17", "m19", "m21", "m41", "m54", "m23", "m26"))

biofilmplot <- ggplot(rel_fit_dat, aes(y = clones, x = rel_fit_dat[,2], group = clones))+
  geom_point(size = 4, shape = 21, color = "darkblue", fill = "white")+
  mytheme+
  geom_vline(xintercept = 0, linetype = "dashed")+
  geom_errorbar(aes(xmin =plt_qnts_dat[,1], xmax =plt_qnts_dat[,3]), width = 0, size =1, color = "darkblue")+
  xlab("Relative change")+
  theme(axis.title.y = element_blank())
ggsave("biofilmJags_coef.pdf", biofilmplot, width = 5, height = 6)

#compared to the previous,method this one slightly diff variation around estimates
# the estimates themselves are very close

#plot as distribution
coef_data <- as.data.frame(biovals)
coef_data_rel <- (coef_data[2:11]+coef_data[,1])/coef_data[,1]
names(coef_data_rel) <- clns[-11]

coef_data_long <- coef_data_rel %>%
  pivot_longer(cols = m4:m79, names_to = "clones", values_to = "coefficients")

coef_data_long$clones <- factor(coef_data_long$clones, c("m4", "m13", "m79", "m17", "m19", "m21", "m41", "m54", "m23", "m26"))

biofilm_rel_coef <- ggplot(coef_data_long, aes(y = clones, x = coefficients, group = clones, 
                           fill = 0.5 - abs(0.5 - stat(ecdf))))+
  geom_vline(xintercept = 1, linetype = "dashed", color = "grey25")+
  stat_density_ridges(geom = "density_ridges_gradient", calc_ecdf = TRUE, 
                      rel_min_height = 0.0005, alpha = 0.5, scale = 2, color = "grey50" 
                      )+
  theme(axis.title.y = element_blank())+
  xlab("Relative change")+
  scale_x_continuous(limits = c(-0.2, 20))+
  mytheme+
   scale_fill_gradient(low = "white", high = "#87CEFF",
                      name = "Tail prob.")
 

ggsave("biofilmJags_coef_dist.pdf", biofilm_rel_coef, width = 5, height = 6)
  

```



# Trade-off exploration - Canan 
```{r}
GrowthData <- read.table("~/Github/SporMut/code/4.GrowthCurves/test/growthData", sep= ",", header = TRUE)
#BiofilmData

GrowthData$clones <- GrowthData$clone
GrowthData <- GrowthData %>% group_by(clones) %>% mutate(id = row_number()) %>% ungroup()

#lengths are different 

tradeoff <- biofilmData %>% 
  dplyr::select(OD550, clones) %>% 
  group_by(clones) %>% 
  mutate(id = row_number()) %>%
  left_join(GrowthData, by = c("clones", "id")) %>% 
  ungroup()

    ggplot(tradeoff, aes(y = log10(OD550+1), x = umax))+
    geom_point()+
      geom_smooth(method="loess")
  
```

